name: Generate Rules
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download and Clean
        run: |
          # Скачиваем список YouTube
          curl -sL https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Services/youtube.lst | sed 's/[[:space:]]//g' | grep -v '^$' > youtube.txt

      - name: Create YAML format
        run: |
          echo "payload:" > youtube.yaml
          sed "s/^/  - '/;s/$/'/" youtube.txt >> youtube.yaml

      - name: Install Mihomo and Convert to MRS
        run: |
          # Прямая ссылка на скачивание актуальной версии без использования API
          # Скачиваем версию для linux-amd64 (совместимая v1 версия)
          curl -L -o mihomo.gz "https://github.com/MetaCubeX/mihomo/releases/latest/download/mihomo-linux-amd64-compatible.gz"
          
          # Распаковываем (это просто сжатый исполняемый файл, а не tar-архив)
          gunzip mihomo.gz
          chmod +x mihomo
          
          # Конвертируем текстовый список в бинарный MRS
          ./mihomo convert-ruleset domain text youtube.txt youtube.mrs

      - name: Push changes
        run: |
          git config --global user.name "Dron3d-Bot"
          git config --global user.email "action@github.com"
          git add youtube.yaml youtube.mrs
          # Если изменений нет, скрипт не упадет (exit 0)
          git commit -m "Manual update: $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push
