name: Generate Rules
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Даем права на запись в репозиторий
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Download and Clean
        run: |
          # Скачиваем список YouTube
          curl -sL https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Services/youtube.lst | sed 's/[[:space:]]//g' | grep -v '^$' > youtube.txt

      - name: Create YAML format
        run: |
          echo "payload:" > youtube.yaml
          sed "s/^/  - '/;s/$/'/" youtube.txt >> youtube.yaml

      - name: Install Mihomo and Convert to MRS
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Используем официальный CLI GitHub для скачивания последней версии
          # Ищем файл для linux-amd64 (формат .gz)
          gh release download --repo MetaCubeX/mihomo --pattern "mihomo-linux-amd64-compatible-*.gz"
          
          # Распаковываем скачанный файл (имя будет содержать версию, используем *)
          gunzip mihomo-linux-amd64-compatible-*.gz
          
          # Переименовываем в короткое 'mihomo' для удобства
          mv mihomo-linux-amd64-compatible-* mihomo
          chmod +x mihomo
          
          # Конвертируем
          ./mihomo convert-ruleset domain text youtube.txt youtube.mrs

      - name: Push changes
        run: |
          git config --global user.name "Dron3d-Bot"
          git config --global user.email "action@github.com"
          git add youtube.yaml youtube.mrs
          git commit -m "Manual update: $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push
